// The `inget reindex` command: rebuild a datatype's vectors under the configured embedder.
//
// This is the recovery path for the one change `inget run` cannot make. A destination table is
// bound to one embedder (D7), so changing models.embedder makes every write fail until the
// binding is replaced — and replacing it is only safe if whatever replaces it also rewrites the
// rows the previous model left. Reindex does both, resumably, and then deletes what the new model
// never wrote.
//
// It needs no generator and spends no generator tokens: the text is already in state.
package main

import (
	"context"
	"fmt"

	"github.com/spf13/cobra"

	"github.com/maxwellcudlitz/inget/internal/cli"
	"github.com/maxwellcudlitz/inget/internal/config"
	"github.com/maxwellcudlitz/inget/internal/destination"
	"github.com/maxwellcudlitz/inget/internal/model"
	"github.com/maxwellcudlitz/inget/internal/pipeline"
	"github.com/maxwellcudlitz/inget/internal/reindex"
)

// reindexOptions are the command's flags.
type reindexOptions struct {
	views        []string
	destinations []string
	force        bool
	batchSize    int
	pruneUnknown bool
}

// reindexCommand builds `inget reindex`.
func reindexCommand() *cobra.Command {
	var opts reindexOptions

	cmd := &cobra.Command{
		Use:   "reindex [datatype]",
		Short: "Re-embed stored view text under the configured embedder",
		Long: "reindex rebinds each destination to the configured embedder, re-embeds the view text\n" +
			"already in state, writes it back, and deletes the rows the new embedder never wrote. It\n" +
			"never calls the generator: a prompt or model change is regenerated by `inget run`, whose\n" +
			"cascade already detects a signature change and prices it in `inget plan`. The pass claims\n" +
			"per-item work rows, so an interrupted reindex resumes where it stopped.",
		Args:         cobra.MaximumNArgs(1),
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runReindex(cmd, args, opts)
		},
	}
	cmd.Flags().StringSliceVar(&opts.views, "view", nil, "restrict the pass to these view names")
	cmd.Flags().StringSliceVar(&opts.destinations, "destination", nil,
		"restrict the pass to these destinations")
	cmd.Flags().BoolVar(&opts.force, "force", false,
		"re-embed views that already carry the configured embedder")
	cmd.Flags().IntVar(&opts.batchSize, "batch-size", reindex.DefaultBatchSize,
		"items claimed and embedded per batch")
	cmd.Flags().BoolVar(&opts.pruneUnknown, "prune-unconfigured", false,
		"also delete rows of datatypes this configuration does not declare that carry another model")
	return cmd
}

// runReindex reindexes every requested datatype and reports what each pass did.
func runReindex(cmd *cobra.Command, args []string, opts reindexOptions) error {
	cfg, err := config.Load(cli.ConfigPath(cmd))
	if err != nil {
		return fmt.Errorf("loading configuration: %w", err)
	}
	datatypes, err := selectDatatypes(cfg, args)
	if err != nil {
		return err
	}

	emb, err := buildEmbedder(cfg)
	if err != nil {
		return err
	}
	store, err := openState(cmd.Context(), cfg)
	if err != nil {
		return err
	}
	defer func() { _ = store.Close() }()

	ctx, cancel, shutdownCh := pipeline.NotifyShutdown(cmd.Context())
	defer cancel()
	ctx = pipeline.WithShutdown(ctx, shutdownCh)

	reports := make([]reindex.Report, 0, len(datatypes))
	for _, dt := range datatypes {
		report, err := reindexDatatype(ctx, cfg, store, emb, dt, opts)
		if err != nil {
			return fmt.Errorf("reindexing %s: %w", dt.Name, err)
		}
		reports = append(reports, report)
		if report.Interrupted {
			break
		}
	}
	if err := pruneUnconfigured(ctx, cfg, emb, datatypes, opts, reports); err != nil {
		return err
	}
	return reportReindex(reports)
}

// reindexDatatype opens the destinations in scope and runs one pass.
func reindexDatatype(ctx context.Context, cfg *config.Config, store reindex.State,
	emb model.Embedder, dt config.Datatype, opts reindexOptions) (reindex.Report, error) {
	if err := checkViews(dt, opts.views); err != nil {
		return reindex.Report{}, err
	}
	names, err := scopedDestinations(dt, opts.destinations)
	if err != nil {
		return reindex.Report{}, err
	}

	dests := map[string]destination.Destination{}
	defer func() {
		for _, sink := range dests {
			_ = sink.Close()
		}
	}()
	for _, name := range names {
		// Unbound on purpose: asserting the binding is what fails when the embedder changed,
		// which is the situation this command exists for.
		sink, err := openDestinationUnbound(ctx, cfg, name)
		if err != nil {
			return reindex.Report{}, err
		}
		dests[name] = sink
	}

	configHash, err := cfg.ConfigHash(dt.Source, dt.Name)
	if err != nil {
		return reindex.Report{}, fmt.Errorf("computing config hash: %w", err)
	}
	return reindex.Run(ctx, reindex.Deps{State: store, Embedder: emb, Destinations: dests},
		reindex.Options{
			Datatype:       dt.Name,
			Destinations:   names,
			Views:          opts.views,
			MetadataFields: dt.MetadataFields,
			ConfigHash:     configHash,
			BatchSize:      opts.batchSize,
			Force:          opts.force,
			MetadataRefs:   injectsMetadata(dt),
		})
}
